name: tsb_main
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.9.2
dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  heroicons: ^0.11.0
  flutter_svg: ^2.0.7
  font_awesome_flutter: ^10.10.0
  google_fonts: ^6.0.0
  table_calendar: ^3.2.0
  intl: ^0.20.2
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  shared_preferences: ^2.3.2 


  tsb_mini: 
    git:
      url: https://github.com/ritz-dev/tsb_mini.git
      ref: staging

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets: 
      - assets/image/hop.png
      - assets/icon/drawer.svg
      - assets/bottom_image/setting.png
      - assets/bottom_image/ticket.png
      - assets/bottom_image/vector.png
      - assets/bottom_image/reward.png
      - assets/image/hop2.png
      - assets/lang/

  fonts:
    - family: FCIconic
      fonts:
        - asset: assets/font/FCIconicRegular.ttf
        - asset: assets/font/FCIconicRegular.otf 
